### ISSUE TITLE
Error when using `chem_lsbo` with `mlm_cnn`

### ISSUE THREAD

**Issue by jiz005** [samuelstanton/lambo#9]
When using command 
``` Shell
python scripts/black_box_opt.py optimizer=lambo optimizer.encoder_obj=lanmt task=chem_lsbo tokenizer=selfies surrogate=single_task_svgp acquisition=ei encoder=mlm_cnn
```
, the following error occurs
```
[2023-03-16 00:23:19,683][root][ERROR] - cannot sample n_sample <= 0 samples
Traceback (most recent call last):
  File "scripts/black_box_opt.py", line 57, in main
    metrics = optimizer.optimize(
  File "lambo_test/lambo/lambo/optimizers/lambo.py", line 179, in optimize
    records = self.surrogate_model.fit(
  File "lambo_test/lambo/lambo/models/gp_models.py", line 416, in fit
    return fit_gp_surrogate(**fit_kwargs)
  File "lambo_test/lambo/lambo/models/gp_utils.py", line 160, in fit_gp_surrogate
    start_metrics.update(lanmt_eval_epoch(surrogate.encoder.model, val_loader, split='val'))
  File "lambo_test/lambo/lambo/models/lanmt.py", line 149, in lanmt_eval_epoch
    src_tok_idxs = corrupt_tok_idxs(tgt_tok_idxs, model.tokenizer, model.max_len_delta)
  File "lambo_test/lambo/lambo/models/lanmt.py", line 18, in corrupt_tok_idxs
    rand_idxs = sample_mask(tgt_tok_idxs, tokenizer, mask_size=max_len_delta)
  File "lambo_test/lambo/lambo/models/mlm.py", line 58, in sample_mask
    mask_idxs = torch.multinomial(mask_weights, mask_size, replacement=False)
RuntimeError: cannot sample n_sample <= 0 samples
```
This seems to be caused by `max_len_delta: 0` argument in `lambo/hydra_config/encoder/mlm_cnn.yaml` which sets the `mask_size` to 0

**Comment by samuelstanton** [comment]
If you're using `optimizer.encoder_obj=lanmt` you should also use `encoder=lanmt_cnn`

https://github.com/samuelstanton/lambo/blob/main/hydra_config/encoder/lanmt_cnn.yaml

**Comment by jiz005** [comment]
Thanks. It is working and I am going to close this issue now.
